POST http://localhost/users HTTP/1.1
Content-Type: application/json

{
    "name": {
        "firstname": "Serverlxess1", 
        "lastname": "Serverless1"
    },
    "status": 100,
    "position": {
      "timestamp": 1582793116170,
      "lat": 56,
      "long": 55
    },
    "subscriptions": [],
    "id": 6,
    "email": "serverless@example.com",
    "password": "serverless"
}
### 

POST http://localhost/services HTTP/1.1
Content-Type: application/json

{
   "id": 1,
   "serviceName" : "Service1",
   "description" : "This is a service that does X",
   "position": {
        "lat": 0,
        "long": 0
    },
    "active":true,
    "settings": ["distance", "quetime"],
    "endpointURL": "http://localhost:7071/api/service1"
}
### Scenario Start 

POST http://localhost/login HTTP/1.1
Content-Type: application/json

{
    "email" : "serverless@example.com",
    "password": "serverless"
}

###
GET http://localhost/services HTTP/1.1

###
POST https://monolith-oscan898.azurewebsites.net/subscriptions HTTP/1.1
Content-Type: application/json

{
   "userID":6,
   "serviceObj": {
       "id": 1,
       "settings": {"distance": 100,  "queuetime": 5}
   }
}
###

###
POST https://monolith-oscan898.azurewebsites.net/checkSubscriptions HTTP/1.1
Content-Type: application/json

{
   "userID":6,
   "position": {
        "lat": 0.5,
        "long": 0
    }
}
###
